const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Plugins.NinePatch,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCreated
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Logo: 0},
	{Tween: 0},
	{spbeyaz: 0},
	{Flash: 0},
	{solTabela: 0},
	{donenyildiz: 0},
	{yildiz: 0},
	{soruzemin: 0},
	{secenek_zemin: 0},
	{Timer: 0},
	{sure_bar_bg: 0},
	{howtoplay: 0},
	{kaynakca: 0},
	{Sine: 0},
	{gulumseyenyildiz: 0},
	{yildiz_kucuk: 0},
	{sure_bar: 0},
	{emegigecenler: 0},
	{meb_logo: 0},
	{btn_tamekran: 0},
	{durum: 0},
	{btn_ses: 0},
	{btn_basla: 0},
	{btn_anasayfa: 0},
	{btn_bilgi: 0},
	{btn_kapat: 0},
	{btn_kaynakca: 0},
	{btn_replay: 0},
	{btn_emegigecenler: 0},
	{Touch: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Browser: 0},
	{AJAX: 0},
	{sorular: 0},
	{sorularSirasi: 0},
	{Audio: 0},
	{Skor: 0},
	{soru: 0},
	{secenekler_text: 0},
	{sure: 0},
	{txt_dogru: 0},
	{txt_skor: 0},
	{txt_toplamsoru: 0},
	{kalanSoru: 0},
	{ButonAilesi: 0},
	{texts: 0},
	{skor: 0},
	{time_bar: 0},
	{sayac: 0},
	{dogru: 0},
	{musicDurum: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {},
	spbeyaz: class extends self.ISpriteInstance {},
	solTabela: class extends self.ISpriteInstance {},
	donenyildiz: class extends self.ISpriteInstance {},
	yildiz: class extends self.ISpriteInstance {},
	soruzemin: class extends self.ISpriteInstance {},
	secenek_zemin: class extends self.ISpriteInstance {},
	sure_bar_bg: class extends self.ISpriteInstance {},
	howtoplay: class extends self.ISpriteInstance {},
	kaynakca: class extends self.ISpriteInstance {},
	gulumseyenyildiz: class extends self.ISpriteInstance {},
	yildiz_kucuk: class extends self.ISpriteInstance {},
	sure_bar: class extends self.IWorldInstance {},
	emegigecenler: class extends self.ISpriteInstance {},
	meb_logo: class extends self.ISpriteInstance {},
	btn_tamekran: class extends self.ISpriteInstance {},
	btn_ses: class extends self.ISpriteInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	btn_anasayfa: class extends self.ISpriteInstance {},
	btn_bilgi: class extends self.ISpriteInstance {},
	btn_kapat: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_replay: class extends self.ISpriteInstance {},
	btn_emegigecenler: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	sorular: class extends self.IArrayInstance {},
	sorularSirasi: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Skor: class extends self.ITextInstance {},
	soru: class extends self.ITextInstance {},
	secenekler_text: class extends self.ITextInstance {},
	sure: class extends self.ITextInstance {},
	txt_dogru: class extends self.ITextInstance {},
	txt_skor: class extends self.ITextInstance {},
	txt_toplamsoru: class extends self.ITextInstance {},
	kalanSoru: class extends self.ITextInstance {},
	ButonAilesi: class extends self.ISpriteInstance {},
	texts: class extends self.ITextInstance {}
}